project_id = "uuijigmwkpmakltymkqe"

[functions.get-vapid-key]
verify_jwt = false

[functions.schedule-notifications]
verify_jwt = false

[functions.send-notification]
verify_jwt = false

[functions.test-notification]
verify_jwt = false

[functions.trigger-instant-notification]
verify_jwt = false
